template_path: templates/example/lambda_function.py
hooks:
  before_create:
    - !s3_package src/example/lambda-py2-deps
  before_update:
    - !s3_package src/example/lambda-py2-deps
parameters:
  Name: {{ environment_config.resource_prefix }}-py2-deps
  Role: !stack_output lambda-role::Arn
sceptre_user_data:
  Runtime: python2.7
  Handler: index.handler
  Code:
    S3Bucket: {{ environment_config.artifacts_bucket }}
    S3Key: lambda/example-py2-deps.zip
    S3ObjectVersion: !s3_version
